### ISSUE TITLE
Mod stops functioning after player dies.

### ISSUE THREAD

**Issue by Cakx** [jmilthedude/FreeLook#2]
After the player dies(and respawns), the free-looking feature does not work anymore, holding down the button will then simply lock the view rotation completly. Only restarting the client helps to regain the mods functionality (until the next death). 

Minecraft: 1.12.2
Mod version: 1.2.1

Forge versions used for testing:
14.23.4.2705 (Recommended)
14.23.4.2747 (Latest)

No other mods installed.

___

Greetings and good luck fixing the mod!

**Comment by jmilthedude** [comment]
Should be resolved. issue: Player was set statically in camera class. Fix in next update (1.2.2)
